### ISSUE TITLE
Little trouble playing 

### ISSUE THREAD

**Issue by Ookamini95** [MorePog/tic-tac-toe#1]
For some reason, the field is a 2x4 +1 board instead of a 3x3 board.

**Comment by Seb-GRAF** [comment]
I can't seem to replicate this bug, mind sharing when this is happening?

**Comment by Ookamini95** [comment]
![Immagine 2022-07-30 084031](https://user-images.githubusercontent.com/109693379/181880386-be37cd46-e651-475e-bf08-7519f4d60049.png)

On chrome and opera this happens, confirmed that on firefox it works perfectly

**Comment by Seb-GRAF** [comment]
This code dates back to when I was starting out, so it's very poorly written. It should be fixed now, I probably wasn't aware of box sizing back then. 😅 Thank you!
